# Generated by Django 5.1.7 on 2025-04-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_eventdetailpage_delete_eventitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailpage',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('event', 'Event')], default='news', help_text='Is this a News or Event item?', max_length=10),
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
