# Generated by Django 5.1.7 on 2025-04-06 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_og_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image used when sharing this page on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image used when sharing this page on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image used when sharing this page on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='eventdetailpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image used when sharing this page on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image used when sharing this page on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Image used when sharing this page on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
