# Generated by Django 5.1.7 on 2025-04-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aboutpage_og_image_contactpage_og_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.'),
        ),
        migrations.AddField(
            model_name='donatepage',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.'),
        ),
        migrations.AddField(
            model_name='eventdetailpage',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.'),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.'),
        ),
    ]
