# Generated by Django 5.1.7 on 2025-05-24 02:37

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_aboutpage_no_index_contactpage_no_index_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('no_index', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('date', models.DateField(help_text='Date the resource was published.', verbose_name='Publication Date')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='A short introduction or summary of the resource.')),
                ('og_image', models.ForeignKey(blank=True, help_text='Image used when sharing this page on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('resource_file', models.ForeignKey(blank=True, help_text='Upload the newsletter or annual report PDF/document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('resource_image', models.ForeignKey(blank=True, help_text='Image to represent the resource (e.g., cover of newsletter).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Resource Page',
                'verbose_name_plural': 'Resource Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ResourcesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('no_index', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Text to describe the resources section.')),
                ('og_image', models.ForeignKey(blank=True, help_text='Image used when sharing this page on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Resources Index Page',
                'verbose_name_plural': 'Resources Index Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
