# Generated by Django 5.1.7 on 2025-06-17 03:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_resourcepage_resourcesindexpage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('no_index', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page.')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Optional introductory text for the FAQ page.', null=True)),
                ('og_image', models.ForeignKey(blank=True, help_text='Image used when sharing this page on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'FAQ Page',
                'verbose_name_plural': 'FAQ Pages',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
