# Generated by Django 5.1.7 on 2026-02-05 03:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_faqpage'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resourcepage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resourcesindexpage',
            options={},
        ),
        migrations.AlterField(
            model_name='eventdetailpage',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('event', 'Event')], default='news', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventdetailpage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='date',
            field=models.DateField(verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='resource_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='resourcepage',
            name='resource_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='resourcesindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
