# Generated by Django 5.1.7 on 2026-02-09 00:01

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_faqpage_options_alter_resourcepage_options_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(default='Transform communities through empowerment', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Transform', max_length=100),
        ),
        migrations.CreateModel(
            name='MissionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('icon_name', models.CharField(default='leaf', help_text="Lucide icon name (e.g., 'leaf', 'shield', 'sparkles')", max_length=50)),
                ('color_class', models.CharField(choices=[('from-primary/20 to-primary/5', 'Green (Primary)'), ('from-secondary/20 to-secondary/5', 'Blue (Secondary)'), ('from-tertiary/20 to-tertiary/5', 'Orange (Tertiary)')], default='from-primary/20 to-primary/5', max_length=100)),
                ('short_description', models.TextField(help_text='Shown on the card front')),
                ('full_details', models.TextField(help_text='Shown in the popup modal')),
                ('target_section_id', models.CharField(blank=True, help_text="ID of the section to scroll to (e.g., 'programs')", max_length=50)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_cards', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
