# Generated by Django 5.1.7 on 2026-02-09 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_hero_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_background_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
        migrations.DeleteModel(
            name='MissionCard',
        ),
    ]
