# Generated by Django 5.1.7 on 2026-02-10 01:27

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_newslettersubscriber'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerypage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='gallerypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='gallery_page',
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='description',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='leadership_text',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='leadership_title',
            field=models.CharField(default='Led by Indigenous Women', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_text',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_title',
            field=models.CharField(default='Our Mission', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_text',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_title',
            field=models.CharField(default='Our Vision', max_length=100),
        ),
        migrations.CreateModel(
            name='AboutPageValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_name', models.CharField(choices=[('heart', 'Heart (Compassion)'), ('users', 'Users (Community)'), ('target', 'Target (Integrity)'), ('award', 'Award (Excellence)'), ('leaf', 'Leaf (Nature)'), ('shield', 'Shield (Protection)')], default='heart', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_values', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='GalleryPage',
        ),
    ]
