# Generated by Django 5.1.7 on 2026-02-10 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_gallerypage_og_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='leadership_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='leadership_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mission_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='mission_title',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='vision_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='vision_title',
        ),
        migrations.DeleteModel(
            name='AboutPageValue',
        ),
    ]
