# Generated by Django 5.1.7 on 2026-02-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_programspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='intro',
        ),
    ]
